// Differential oracle preserves the former per-page map.find Contains path.
// No texture/GPU traffic is generated by host address-range validation.
#include "memory/dram_address_space.h"

#include <algorithm>
#include <array>
#include <chrono>
#include <cstdint>
#include <iostream>
#include <limits>
#include <map>
#include <numeric>
#include <random>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

using pvrgpu::stub::DramAddressSpace;
namespace {
constexpr uint64_t kMaximum = UINT64_MAX;
constexpr size_t kPage = DramAddressSpace::kPageBytes;
uint64_t checks = 0;
void Check(bool value, const char *message) {
  if (!value) throw std::runtime_error(message);
  ++checks;
}
template <typename Function> unsigned Outcome(Function function) {
  try { function(); return 0; }
  catch (const std::overflow_error &) { return 1; }
  catch (const std::invalid_argument &) { return 2; }
  catch (const std::runtime_error &) { return 3; }
}

struct Reference {
  std::map<uint64_t, std::array<uint8_t, kPage>> pages;
  // Keep this exact old search/overflow order as the independent oracle.
  bool Contains(uint64_t address, size_t bytes) const noexcept {
    if (bytes == 0 || bytes > kMaximum - address) return false;
    const uint64_t end = address + bytes;
    uint64_t page = address - address % kPage;
    while (page < end) {
      if (pages.find(page) == pages.end()) return false;
      if (kPage > kMaximum - page) return false;
      page += kPage;
    }
    return true;
  }
  void Write(uint64_t address, const uint8_t *source, size_t bytes) {
    if ((!source && bytes) || !bytes) throw std::invalid_argument("invalid write");
    if (bytes > kMaximum - address) throw std::overflow_error("wrapped write");
    uint64_t page = address - address % kPage;
    const uint64_t end = address + bytes;
    while (page < end) {
      pages.try_emplace(page);
      // The old backing inserts the final page before this refusal. Contains
      // must still reject a page-advance overflow, even when that page exists.
      if (kPage > kMaximum - page) throw std::overflow_error("page overflow");
      page += kPage;
    }
    for (size_t i = 0; i < bytes; ++i) {
      const auto current = address + i;
      pages.at(current - current % kPage)[current % kPage] = source[i];
    }
  }
  std::vector<uint8_t> Read(uint64_t address, size_t bytes) const {
    if (!bytes) throw std::invalid_argument("empty read");
    if (bytes > kMaximum - address) throw std::overflow_error("wrapped read");
    std::vector<uint8_t> result(bytes);
    for (size_t i = 0; i < bytes; ++i) {
      const auto current = address + i;
      const auto found = pages.find(current - current % kPage);
      if (found == pages.end()) throw std::runtime_error("missing page");
      result[i] = found->second[current % kPage];
    }
    return result;
  }
};

void Query(const DramAddressSpace &actual, const Reference &reference,
           uint64_t address, size_t bytes) {
  const auto resident = actual.resident_pages();
  Check(actual.Contains(address, bytes) == reference.Contains(address, bytes),
        "iterator Contains differs from per-page find oracle");
  Check(actual.resident_pages() == resident && resident == reference.pages.size(),
        "Contains changed backing ownership/page count");
}
void Read(const DramAddressSpace &actual, const Reference &reference,
          uint64_t address, size_t bytes) {
  std::vector<uint8_t> a, b;
  const auto x = Outcome([&] { a = actual.Read(address, bytes); });
  const auto y = Outcome([&] { b = reference.Read(address, bytes); });
  Check(x == y && (x != 0 || a == b), "backing read/exception changed");
}
void Write(DramAddressSpace &actual, Reference &reference,
           uint64_t address, size_t bytes, unsigned seed, bool null_source = false) {
  std::vector<uint8_t> values(bytes);
  for (size_t i = 0; i < bytes; ++i) values[i] = uint8_t(seed + i * 17);
  const auto *source = null_source ? nullptr : values.data();
  const auto a = Outcome([&] { actual.Write(address, source, bytes); });
  const auto b = Outcome([&] { reference.Write(address, source, bytes); });
  Check(a == b && actual.resident_pages() == reference.pages.size(),
        "backing write/exception/page ownership changed");
  Query(actual, reference, address, bytes);
  if (bytes <= 1024) Read(actual, reference, address, bytes);
}
void Boundaries(const DramAddressSpace &actual, const Reference &reference) {
  for (uint64_t address : {UINT64_C(0), UINT64_C(1), UINT64_C(126), UINT64_C(127),
                          UINT64_C(128), UINT64_C(129), UINT64_C(255), UINT64_C(256),
                          kMaximum - 256, kMaximum - 255, kMaximum - 128,
                          kMaximum - 127, kMaximum - 1, kMaximum})
    for (size_t bytes : {size_t(0), size_t(1), size_t(2), size_t(127), size_t(128),
                        size_t(129), size_t(255), size_t(256), size_t(257),
                        std::numeric_limits<size_t>::max()})
      Query(actual, reference, address, bytes);
}
void RandomQueries(const DramAddressSpace &actual, const Reference &reference,
                   std::mt19937_64 &random, unsigned count) {
  for (unsigned i = 0; i < count; ++i) {
    const uint64_t address = i % 7 == 0 ? kMaximum - random() % 16384 : random() % 16384;
    const size_t bytes = i % 11 == 0 ? size_t(random()) : size_t(random() % 2048);
    Query(actual, reference, address, bytes);
    if (i % 17 == 0 && bytes <= 2048) Read(actual, reference, address, bytes);
  }
}

void TestOrdersHolesAndOwnership() {
  std::mt19937_64 random(0x64a53b1c);
  for (unsigned order = 0; order < 3; ++order) {
    DramAddressSpace actual;
    Reference reference;
    Boundaries(actual, reference);
    std::vector<unsigned> pages(96);
    std::iota(pages.begin(), pages.end(), 0U);
    if (order == 1) std::reverse(pages.begin(), pages.end());
    if (order == 2) std::shuffle(pages.begin(), pages.end(), random);
    for (unsigned page : pages) {
      if (page % 7 == 3) continue; // Both interior and edge holes stay explicit.
      Write(actual, reference, page * kPage + page % kPage, 1, page);
      RandomQueries(actual, reference, random, 32);
    }
    for (unsigned begin = 0; begin < 96; ++begin)
      for (unsigned end = begin; end < 96; ++end)
        for (unsigned offset : {0U, 1U, 127U})
          Query(actual, reference, begin * kPage + offset,
                (end - begin) * kPage + 1);
    auto copied = actual;
    auto copy_reference = reference;
    RandomQueries(copied, copy_reference, random, 1024);
    Write(copied, copy_reference, 3 * kPage, kPage, 99);
    Check(copied.Contains(3 * kPage, kPage) && !actual.Contains(3 * kPage, kPage),
          "copied backing is not independently owned");
    DramAddressSpace assigned;
    Reference assigned_reference;
    Write(assigned, assigned_reference, 65536, kPage, 12);
    assigned = copied;
    assigned_reference = copy_reference;
    RandomQueries(assigned, assigned_reference, random, 1024);
    auto moved = std::move(assigned);
    auto moved_reference = std::move(assigned_reference);
    RandomQueries(moved, moved_reference, random, 1024);
    DramAddressSpace move_assigned;
    Reference move_assigned_reference;
    move_assigned = std::move(moved);
    move_assigned_reference = std::move(moved_reference);
    Boundaries(move_assigned, move_assigned_reference);
    RandomQueries(move_assigned, move_assigned_reference, random, 1024);
    // A moved-from object's map is valid but its contents are unspecified.
    // Reset it explicitly before verifying subsequent insert/query behavior.
    moved = DramAddressSpace{};
    moved_reference = Reference{};
    Write(moved, moved_reference, 17, kPage + 5, 27);
    Boundaries(moved, moved_reference);
    for (unsigned page : pages)
      if (page % 7 == 3) Write(actual, reference, page * kPage, 1, 77);
    Check(actual.Contains(0, pages.size() * kPage), "filled holes remained stale");
    RandomQueries(actual, reference, random, 2048);
  }
}
void TestRandomWritesAndExtremes() {
  std::mt19937_64 random(0x194157ffff);
  DramAddressSpace actual;
  Reference reference;
  for (unsigned i = 0; i < 1024; ++i) {
    const uint64_t address = i % 5 == 0 ? kMaximum - random() % 16384 : random() % 16384;
    Write(actual, reference, address, size_t(random() % 257), unsigned(random()), i % 29 == 0);
    RandomQueries(actual, reference, random, 48);
    if (i % 31 == 0) Boundaries(actual, reference);
  }
  for (uint64_t address : {kMaximum, kMaximum - 1, kMaximum - 127,
                          kMaximum - 128, kMaximum - 255, kMaximum - 256})
    for (size_t bytes : {size_t(0), size_t(1), size_t(127), size_t(128), size_t(129), size_t(256)}) {
      Write(actual, reference, address, bytes, 61);
      Boundaries(actual, reference);
    }
  Check(!actual.Contains(kMaximum - 127, 1), "page-advance overflow was silently accepted");
}
void Benchmark() {
  for (size_t bytes : {size_t(8) << 20, size_t(33) << 20}) {
    DramAddressSpace actual;
    Reference reference;
    Write(actual, reference, 0x200000, bytes, 29);
    const auto run = [&](bool old) {
      const auto start = std::chrono::steady_clock::now();
      for (unsigned i = 0; i < 16; ++i)
        Check(old ? reference.Contains(0x200000 + i, bytes - i)
                  : actual.Contains(0x200000 + i, bytes - i), "benchmark lost backing pages");
      return std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - start).count();
    };
    const double old = run(true), optimized = run(false);
    std::cout << "informational host Contains bytes=" << bytes << " find_ms=" << old
              << " iterator_ms=" << optimized << " ratio=" << old / optimized
              << " (not GPU work or timing assertion)\n";
  }
}
} // namespace
int main(int argc, char **argv) {
  static_assert(noexcept(std::declval<const DramAddressSpace &>().Contains(0, 1)));
  try {
    TestOrdersHolesAndOwnership();
    TestRandomWritesAndExtremes();
    if (argc == 2 && std::string(argv[1]) == "--benchmark") Benchmark();
    std::cout << "DRAM Contains differential PASS checks=" << checks << '\n';
    return 0;
  } catch (const std::exception &error) {
    std::cerr << error.what() << '\n';
    return 1;
  }
}
