// Differential oracle preserves the former per-page map.find Contains path.
// No texture/GPU traffic is generated by host address-range validation.
#include "memory/dram_address_space.h"

#include <algorithm>
#include <array>
#include <chrono>
#include <cstdint>
#include <iostream>
#include <limits>
#include <map>
#include <numeric>
#include <random>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

using pvrgpu::stub::DramAddressSpace;
namespace {
constexpr uint64_t kMaximum = UINT64_MAX;
constexpr size_t kPage = DramAddressSpace::kPageBytes;
uint64_t checks = 0;
void Check(bool value, const char *message) {
  if (!value) throw std::runtime_error(message);
  ++checks;
}
template <typename Function> unsigned Outcome(Function function) {
  try { function(); return 0; }
  catch (const std::overflow_error &) { return 1; }
  catch (const std::invalid_argument &) { return 2; }
  catch (const std::runtime_error &) { return 3; }
}

struct Reference {
  std::map<uint64_t, std::array<uint8_t, kPage>> pages;
  // Keep this exact old search/overflow order as the independent oracle.
  bool Contains(uint64_t address, size_t bytes) const noexcept {
    if (bytes == 0 || bytes > kMaximum - address) return false;
    const uint64_t end = address + bytes;
    uint64_t page = address - address % kPage;
    while (page < end) {
      if (pages.find(page) == pages.end()) return false;
      if (kPage > kMaximum - page) return false;
      page += kPage;
    }
    return true;
  }
  // Immediate pre-cache implementation: one seek followed by an explicit
  // consecutive-page walk. The independent per-page find oracle above remains
  // authoritative for all functional tests; this path is only a benchmark.
  bool ContainsIterator(uint64_t address, size_t bytes) const noexcept {
    if (bytes == 0 || bytes > kMaximum - address) return false;
    const uint64_t end = address + bytes;
    uint64_t page = address - address % kPage;
    auto resident = pages.find(page);
    while (page < end) {
      if (resident == pages.end() || resident->first != page) return false;
      if (kPage > kMaximum - page) return false;
      page += kPage;
      ++resident;
    }
    return true;
  }
  void Write(uint64_t address, const uint8_t *source, size_t bytes) {
    if ((!source && bytes) || !bytes) throw std::invalid_argument("invalid write");
    if (bytes > kMaximum - address) throw std::overflow_error("wrapped write");
    uint64_t page = address - address % kPage;
    const uint64_t end = address + bytes;
    while (page < end) {
      pages.try_emplace(page);
      // The old backing inserts the final page before this refusal. Contains
      // must still reject a page-advance overflow, even when that page exists.
      if (kPage > kMaximum - page) throw std::overflow_error("page overflow");
      page += kPage;
    }
    for (size_t i = 0; i < bytes; ++i) {
      const auto current = address + i;
      pages.at(current - current % kPage)[current % kPage] = source[i];
    }
  }
  std::vector<uint8_t> Read(uint64_t address, size_t bytes) const {
    if (!bytes) throw std::invalid_argument("empty read");
    if (bytes > kMaximum - address) throw std::overflow_error("wrapped read");
    std::vector<uint8_t> result(bytes);
    for (size_t i = 0; i < bytes; ++i) {
      const auto current = address + i;
      const auto found = pages.find(current - current % kPage);
      if (found == pages.end()) throw std::runtime_error("missing page");
      result[i] = found->second[current % kPage];
    }
    return result;
  }
};

void Query(const DramAddressSpace &actual, const Reference &reference,
           uint64_t address, size_t bytes) {
  const auto resident = actual.resident_pages();
  Check(actual.Contains(address, bytes) == reference.Contains(address, bytes),
        "Contains differs from per-page find oracle");
  Check(actual.resident_pages() == resident && resident == reference.pages.size(),
        "Contains changed backing ownership/page count");
}
void Read(const DramAddressSpace &actual, const Reference &reference,
          uint64_t address, size_t bytes) {
  std::vector<uint8_t> a, b;
  const auto x = Outcome([&] { a = actual.Read(address, bytes); });
  const auto y = Outcome([&] { b = reference.Read(address, bytes); });
  Check(x == y && (x != 0 || a == b), "backing read/exception changed");
}
void Write(DramAddressSpace &actual, Reference &reference,
           uint64_t address, size_t bytes, unsigned seed, bool null_source = false) {
  std::vector<uint8_t> values(bytes);
  for (size_t i = 0; i < bytes; ++i) values[i] = uint8_t(seed + i * 17);
  const auto *source = null_source ? nullptr : values.data();
  const auto a = Outcome([&] { actual.Write(address, source, bytes); });
  const auto b = Outcome([&] { reference.Write(address, source, bytes); });
  Check(a == b && actual.resident_pages() == reference.pages.size(),
        "backing write/exception/page ownership changed");
  Query(actual, reference, address, bytes);
  if (bytes <= 1024) Read(actual, reference, address, bytes);
}
void Boundaries(const DramAddressSpace &actual, const Reference &reference) {
  for (uint64_t address : {UINT64_C(0), UINT64_C(1), UINT64_C(126), UINT64_C(127),
                          UINT64_C(128), UINT64_C(129), UINT64_C(255), UINT64_C(256),
                          kMaximum - 256, kMaximum - 255, kMaximum - 128,
                          kMaximum - 127, kMaximum - 1, kMaximum})
    for (size_t bytes : {size_t(0), size_t(1), size_t(2), size_t(127), size_t(128),
                        size_t(129), size_t(255), size_t(256), size_t(257),
                        std::numeric_limits<size_t>::max()})
      Query(actual, reference, address, bytes);
}
void RandomQueries(const DramAddressSpace &actual, const Reference &reference,
                   std::mt19937_64 &random, unsigned count) {
  for (unsigned i = 0; i < count; ++i) {
    const uint64_t address = i % 7 == 0 ? kMaximum - random() % 16384 : random() % 16384;
    const size_t bytes = i % 11 == 0 ? size_t(random()) : size_t(random() % 2048);
    Query(actual, reference, address, bytes);
    if (i % 17 == 0 && bytes <= 2048) Read(actual, reference, address, bytes);
  }
}

void TestOrdersHolesAndOwnership() {
  std::mt19937_64 random(0x64a53b1c);
  for (unsigned order = 0; order < 3; ++order) {
    DramAddressSpace actual;
    Reference reference;
    Boundaries(actual, reference);
    std::vector<unsigned> pages(96);
    std::iota(pages.begin(), pages.end(), 0U);
    if (order == 1) std::reverse(pages.begin(), pages.end());
    if (order == 2) std::shuffle(pages.begin(), pages.end(), random);
    for (unsigned page : pages) {
      if (page % 7 == 3) continue; // Both interior and edge holes stay explicit.
      Write(actual, reference, page * kPage + page % kPage, 1, page);
      RandomQueries(actual, reference, random, 32);
    }
    for (unsigned begin = 0; begin < 96; ++begin)
      for (unsigned end = begin; end < 96; ++end)
        for (unsigned offset : {0U, 1U, 127U})
          Query(actual, reference, begin * kPage + offset,
                (end - begin) * kPage + 1);
    auto copied = actual;
    auto copy_reference = reference;
    RandomQueries(copied, copy_reference, random, 1024);
    Write(copied, copy_reference, 3 * kPage, kPage, 99);
    Check(copied.Contains(3 * kPage, kPage) && !actual.Contains(3 * kPage, kPage),
          "copied backing is not independently owned");
    DramAddressSpace assigned;
    Reference assigned_reference;
    Write(assigned, assigned_reference, 65536, kPage, 12);
    assigned = copied;
    assigned_reference = copy_reference;
    RandomQueries(assigned, assigned_reference, random, 1024);
    auto moved = std::move(assigned);
    auto moved_reference = std::move(assigned_reference);
    RandomQueries(moved, moved_reference, random, 1024);
    DramAddressSpace move_assigned;
    Reference move_assigned_reference;
    move_assigned = std::move(moved);
    move_assigned_reference = std::move(moved_reference);
    Boundaries(move_assigned, move_assigned_reference);
    RandomQueries(move_assigned, move_assigned_reference, random, 1024);
    // A moved-from object's map is valid but its contents are unspecified.
    // Reset it explicitly before verifying subsequent insert/query behavior.
    moved = DramAddressSpace{};
    moved_reference = Reference{};
    Write(moved, moved_reference, 17, kPage + 5, 27);
    Boundaries(moved, moved_reference);
    for (unsigned page : pages)
      if (page % 7 == 3) Write(actual, reference, page * kPage, 1, 77);
    Check(actual.Contains(0, pages.size() * kPage), "filled holes remained stale");
    RandomQueries(actual, reference, random, 2048);
  }
}
void TestRandomWritesAndExtremes() {
  std::mt19937_64 random(0x194157ffff);
  DramAddressSpace actual;
  Reference reference;
  for (unsigned i = 0; i < 1024; ++i) {
    const uint64_t address = i % 5 == 0 ? kMaximum - random() % 16384 : random() % 16384;
    Write(actual, reference, address, size_t(random() % 257), unsigned(random()), i % 29 == 0);
    RandomQueries(actual, reference, random, 48);
    if (i % 31 == 0) Boundaries(actual, reference);
  }
  for (uint64_t address : {kMaximum, kMaximum - 1, kMaximum - 127,
                          kMaximum - 128, kMaximum - 255, kMaximum - 256})
    for (size_t bytes : {size_t(0), size_t(1), size_t(127), size_t(128), size_t(129), size_t(256)}) {
      Write(actual, reference, address, bytes, 61);
      Boundaries(actual, reference);
    }
  Check(!actual.Contains(kMaximum - 127, 1), "page-advance overflow was silently accepted");
}

void TestPrimedProofSubrangesAndHoles() {
  DramAddressSpace actual;
  Reference reference;
  constexpr uint64_t base = 0x10000;
  constexpr size_t bytes = 8 * kPage;
  const std::vector<uint8_t> initial(bytes, 41);
  // Deliberately bypass the Write helper, whose differential Query would
  // already prime an aligned proof before the unaligned first query below.
  actual.Write(base, initial.data(), initial.size());
  reference.Write(base, initial.data(), initial.size());
  Check(actual.resident_pages() == reference.pages.size() &&
            actual.resident_pages() == bytes / kPage,
        "unaligned proof fixture has unexpected backing pages");
  // Prime an unaligned query, then test prefix/interior/suffix ranges including
  // bytes outside that first query but within the same resident backing pages.
  Query(actual, reference, base + 17, bytes - 31);
  for (unsigned repeat = 0; repeat < 3; ++repeat) {
    Query(actual, reference, base, 17);
    Query(actual, reference, base, 2 * kPage);
    Query(actual, reference, base + kPage - 1, 3 * kPage + 2);
    Query(actual, reference, base + 3 * kPage + 19, 2 * kPage - 37);
    Query(actual, reference, base + bytes - 29, 29);
    Query(actual, reference, base + bytes - kPage, kPage);
    Query(actual, reference, base, bytes);
    Query(actual, reference, base + bytes, 1);
    Query(actual, reference, base - 1, bytes + 1);
    Query(actual, reference, base, bytes + 1);
    Query(actual, reference, base + 1, 0);
  }

  constexpr uint64_t hole_base = 0x30000;
  Write(actual, reference, hole_base, 2 * kPage, 17);
  Write(actual, reference, hole_base + 3 * kPage, 2 * kPage, 18);
  for (unsigned repeat = 0; repeat < 3; ++repeat) {
    Query(actual, reference, hole_base, 2 * kPage);
    Query(actual, reference, hole_base + 3 * kPage, 2 * kPage);
    Query(actual, reference, hole_base, 5 * kPage);
    Query(actual, reference, hole_base + 2 * kPage - 1, kPage + 2);
    Query(actual, reference, hole_base + 2 * kPage, 1);
  }
  Check(!actual.Contains(hole_base, 5 * kPage), "separate proofs bridged a missing page");
  Write(actual, reference, hole_base + 2 * kPage, 1, 99);
  Query(actual, reference, hole_base, 5 * kPage);
  Check(actual.Contains(hole_base, 5 * kPage), "prior misses survived filling a hole");

  // More distinct positive spans than the bounded cache can retain. Eviction
  // must only change performance; it cannot join the intervening empty pages.
  constexpr uint64_t sparse_base = 0x50000;
  for (unsigned page = 0; page < 96; ++page)
    Write(actual, reference, sparse_base + page * 2 * kPage, 1, page);
  for (unsigned page = 0; page < 96; ++page)
    Query(actual, reference, sparse_base + page * 2 * kPage, kPage);
  for (unsigned page = 96; page-- > 0;) {
    Query(actual, reference, sparse_base + page * 2 * kPage, kPage);
    Query(actual, reference, sparse_base + page * 2 * kPage, kPage + 1);
    Query(actual, reference, sparse_base + (page * 2 + 1) * kPage, 1);
  }
  Query(actual, reference, base, bytes);
}

void TestPrimedProofFailedTopPageWrite() {
  DramAddressSpace actual;
  Reference reference;
  constexpr uint64_t penultimate_page = kMaximum - (2 * kPage - 1);
  constexpr uint64_t final_page = kMaximum - (kPage - 1);
  Write(actual, reference, penultimate_page, kPage, 73);
  Query(actual, reference, penultimate_page, kPage);
  Check(actual.resident_pages() == 1, "top-page fixture initially has unexpected pages");
  // EnsureRange inserts the final backing page, then refuses page-advance
  // overflow before copying any payload. Existing positive proofs remain true,
  // but the newly inserted top page must never become a valid Contains proof.
  Write(actual, reference, final_page - 8, 16, 91);
  Check(actual.resident_pages() == 2, "failed top-page write lost its documented partial insertion");
  for (unsigned repeat = 0; repeat < 3; ++repeat) {
    Query(actual, reference, penultimate_page, kPage);
    Query(actual, reference, penultimate_page + 7, kPage - 7);
    Query(actual, reference, final_page - 1, 1);
    Query(actual, reference, final_page - 1, 2);
    Query(actual, reference, final_page, 1);
    Query(actual, reference, final_page, kPage - 1);
    Query(actual, reference, penultimate_page, 2 * kPage - 1);
    Query(actual, reference, kMaximum - 1, 1);
    Query(actual, reference, kMaximum, 1);
  }
  Read(actual, reference, final_page - 8, 16);
  Check(!actual.Contains(final_page, 1), "partial failed write installed a false positive proof");
}

void CheckMovedFrom(const DramAddressSpace &actual, const Reference &reference,
                    uint64_t old_base, size_t bytes) {
  // Both objects were independently subjected to the same std::map move.
  // Query before resetting: a stale positive cache cannot claim removed pages.
  Check(actual.resident_pages() == reference.pages.size(), "moved-from backing differs from independent map move");
  Query(actual, reference, old_base, bytes);
  Query(actual, reference, old_base + 1, 1);
  Query(actual, reference, old_base + bytes - 1, 1);
  if (actual.resident_pages() == 0)
    Check(!actual.Contains(old_base, bytes), "empty moved-from backing retained a positive proof");
  Boundaries(actual, reference);
}

void TestPrimedProofCopyMoveAndReset() {
  constexpr uint64_t a_base = 0x1000;
  constexpr uint64_t b_base = 0x8000;
  constexpr uint64_t c_base = 0x10000;
  constexpr size_t bytes = 6 * kPage;
  DramAddressSpace actual, other;
  Reference reference, other_reference;
  Write(actual, reference, a_base, bytes, 1);
  Write(other, other_reference, b_base, bytes, 2);
  Query(actual, reference, a_base, bytes);
  Query(other, other_reference, b_base, bytes);
  Check(actual.resident_pages() == other.resident_pages(), "equal-count copy fixture invalid");
  actual = other;
  reference = other_reference;
  Query(actual, reference, a_base, bytes);
  Query(actual, reference, b_base, bytes);
  Check(!actual.Contains(a_base, 1), "copy assignment retained a disjoint old proof");

  DramAddressSpace copied(actual);
  Reference copied_reference(reference);
  Query(copied, copied_reference, b_base, bytes);
  Write(copied, copied_reference, c_base, kPage, 11);
  Check(copied.Contains(c_base, kPage) && !actual.Contains(c_base, 1),
        "primed copy does not own its pages independently");
  Write(copied, copied_reference, b_base + 23, 17, 29);
  Read(actual, reference, b_base, bytes);
  Read(copied, copied_reference, b_base, bytes);

  // Use aliases to exercise intentional self assignment without compiler
  // self-assignment warnings. The explicit class contract preserves backing.
  DramAddressSpace &self = actual;
  actual = self;
  Query(actual, reference, b_base, bytes);
  actual = std::move(self);
  Query(actual, reference, b_base, bytes);
  Read(actual, reference, b_base, bytes);

  DramAddressSpace moved(std::move(actual));
  Reference moved_reference(std::move(reference));
  Query(moved, moved_reference, b_base, bytes);
  CheckMovedFrom(actual, reference, b_base, bytes);
  Write(actual, reference, a_base, bytes, 37);
  Query(actual, reference, a_base, bytes);
  Check(actual.resident_pages() == moved.resident_pages(), "equal-count move fixture invalid");
  actual = std::move(moved);
  reference = std::move(moved_reference);
  Query(actual, reference, a_base, bytes);
  Query(actual, reference, b_base, bytes);
  Check(!actual.Contains(a_base, 1), "move assignment retained a disjoint old proof");
  CheckMovedFrom(moved, moved_reference, b_base, bytes);

  Query(actual, reference, b_base, bytes);
  actual = DramAddressSpace{};
  reference = Reference{};
  Query(actual, reference, b_base, bytes);
  Check(actual.resident_pages() == 0 && !actual.Contains(b_base, 1),
        "reset retained backing or a stale positive proof");
  Write(actual, reference, c_base, bytes, 43);
  Query(actual, reference, c_base, bytes);
  Query(actual, reference, b_base, bytes);
  Read(other, other_reference, b_base, bytes);
}

using BenchmarkQuery = bool (*)(const void *, uint64_t, size_t);
bool BenchmarkFind(const void *object, uint64_t address, size_t bytes) {
  return static_cast<const Reference *>(object)->Contains(address, bytes);
}
bool BenchmarkIterator(const void *object, uint64_t address, size_t bytes) {
  return static_cast<const Reference *>(object)->ContainsIterator(address, bytes);
}
bool BenchmarkActual(const void *object, uint64_t address, size_t bytes) {
  return static_cast<const DramAddressSpace *>(object)->Contains(address, bytes);
}

void Benchmark() {
  for (size_t bytes : {size_t(8) << 20, size_t(33) << 20}) {
    DramAddressSpace actual;
    Reference reference;
    Write(actual, reference, 0x200000, bytes, 29);
    const auto run = [&](BenchmarkQuery function, const void *object,
                         unsigned repetitions, bool exact) {
      // Every candidate uses the same volatile indirect call and accumulator.
      // This prevents hoisting the repeated pure oracle out of its timed loop.
      BenchmarkQuery volatile query = function;
      unsigned matches = 0;
      const auto start = std::chrono::steady_clock::now();
      for (unsigned i = 0; i < repetitions; ++i) {
        const auto offset = exact ? 0 : i;
        matches += query(object, 0x200000 + offset, bytes - offset);
      }
      const auto elapsed = std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - start).count();
      Check(matches == repetitions, "benchmark lost backing pages");
      return elapsed;
    };
    const double old = run(BenchmarkFind, &reference, 16, false);
    const double optimized = run(BenchmarkActual, &actual, 16, false);
    std::cout << "informational host Contains bytes=" << bytes << " find_ms=" << old
              << " optimized_ms=" << optimized << " ratio=" << old / optimized
              << " (not GPU work or timing assertion)\n";
    // Prime both paths identically outside timing. They query the same address,
    // byte count, resident pages, and repetition count in alternating order.
    Check(reference.ContainsIterator(0x200000, bytes) && actual.Contains(0x200000, bytes),
          "exact hot-range benchmark priming failed");
    constexpr unsigned repetitions = 64;
    double iterator_ms = 0, cached_ms = 0;
    for (unsigned trial = 0; trial < 2; ++trial) {
      if (trial == 0) {
        iterator_ms += run(BenchmarkIterator, &reference, repetitions, true);
        cached_ms += run(BenchmarkActual, &actual, repetitions, true);
      } else {
        cached_ms += run(BenchmarkActual, &actual, repetitions, true);
        iterator_ms += run(BenchmarkIterator, &reference, repetitions, true);
      }
    }
    std::cout << "informational exact repeated host Contains bytes=" << bytes
              << " queries=" << 2 * repetitions << " iterator_ms=" << iterator_ms
              << " cached_ms=" << cached_ms << " ratio=" << iterator_ms / cached_ms
              << " (same repetitions; host query only, not frame speedup or timing assertion)\n";
  }
}
} // namespace
int main(int argc, char **argv) {
  static_assert(noexcept(std::declval<const DramAddressSpace &>().Contains(0, 1)));
  try {
    TestOrdersHolesAndOwnership();
    TestRandomWritesAndExtremes();
    TestPrimedProofSubrangesAndHoles();
    TestPrimedProofFailedTopPageWrite();
    TestPrimedProofCopyMoveAndReset();
    if (argc == 2 && std::string(argv[1]) == "--benchmark") Benchmark();
    std::cout << "DRAM Contains differential PASS checks=" << checks << '\n';
    return 0;
  } catch (const std::exception &error) {
    std::cerr << error.what() << '\n';
    return 1;
  }
}
