/*
 * Development-time generator for the GLBench conditionals PCO programs.
 *
 * The generated bytes come only from Mesa's public PowerVR PCO backend.  The
 * shader shape mirrors the final NIR observed while replaying the pinned
 * glmark2 conditionals capture: one R32G32B32_FLOAT position attribute, a
 * mat4 vertex constant block, framebuffer-position Y transform constants,
 * and the source fract/compare/select arithmetic in both stages.
 *
 * This native C utility is intentionally not part of the runtime.  It is a
 * reproducible decoder/ISS bring-up probe for the pinned Mesa compiler.
 */

#include "common/pvr_device_info.h"
#include "nir/nir.h"
#include "nir/nir_builder.h"
#include "nir/nir_builder_opcodes.h"
#include "pco/pco.h"
#include "pco/pco_data.h"
#include "util/ralloc.h"

#include <errno.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

static nir_shader *build_vertex_shader(void)
{
   nir_builder b = nir_builder_init_simple_shader(MESA_SHADER_VERTEX,
                                                   pco_nir_options(),
                                                   "glbench_conditionals_vs");

   nir_variable *position_in = nir_variable_create(b.shader,
                                                    nir_var_shader_in,
                                                    glsl_vec4_type(),
                                                    "position");
   position_in->data.location = VERT_ATTRIB_GENERIC0;

   nir_variable *position_out = nir_variable_create(b.shader,
                                                     nir_var_shader_out,
                                                     glsl_vec4_type(),
                                                     "gl_Position");
   position_out->data.location = VARYING_SLOT_POS;
   position_out->data.precision = GLSL_PRECISION_MEDIUM;

   nir_def *position = nir_load_input(
      &b,
      4,
      32,
      nir_imm_int(&b, 0),
      .base = 0,
      .range = 1,
      .component = 0,
      .dest_type = nir_type_float32,
      .io_semantics = (nir_io_semantics){
         .location = VERT_ATTRIB_GENERIC0,
         .num_slots = 1,
      });

   nir_def *x = nir_channel(&b, position, 0);
   nir_def *fract_x = nir_ffract(&b, x);
   nir_def *condition = nir_fge(&b, fract_x, nir_imm_float(&b, 0.5f));
   /* Keep the captured Gallium NIR's operand orientation.  FMUL is
    * commutative, but PCO intentionally preserves source order in its
    * encoded instruction groups. */
   nir_def *twice = nir_ffract(
      &b, nir_fmul(&b, nir_imm_float(&b, 2.0f), fract_x));
   nir_def *thrice = nir_ffract(
      &b, nir_fmul(&b, nir_imm_float(&b, 3.0f), fract_x));
   nir_def *selected = nir_bcsel(&b, condition, twice, thrice);
   nir_def *y = nir_fadd(&b,
                         nir_channel(&b, position, 1),
                         nir_fmul(&b,
                                  nir_fmul(&b,
                                           nir_imm_float(&b, 0.1f),
                                           selected),
                                  fract_x));

   nir_def *result = NULL;
   nir_def *position_components[4] = {
      x,
      y,
      nir_channel(&b, position, 2),
      nir_imm_float(&b, 1.0f),
   };
   for (unsigned row = 0; row < 4; ++row) {
      /* NIR load_push_constant offsets are bytes. pco_nir_lower_io() turns
       * them into dword indices before PCO gathers/allocates shareds. */
      nir_def *matrix_row = nir_load_push_constant(&b,
                                                    4,
                                                    32,
                                                    nir_imm_int(&b, row * 16),
                                                    .base = 0,
                                                    .range = 16);
      nir_def *term = nir_fmul(&b, matrix_row, position_components[row]);
      result = result ? nir_fadd(&b, result, term) : term;
   }

   nir_store_output(&b,
                    result,
                    nir_imm_int(&b, 0),
                    .base = 0,
                    .range = 1,
                    .write_mask = 0xf,
                    .component = 0,
                    .src_type = nir_type_float32,
                    .io_semantics = (nir_io_semantics){
                       .location = VARYING_SLOT_POS,
                       .num_slots = 1,
                    });
   nir_jump(&b, nir_jump_return);
   return b.shader;
}

static nir_shader *build_fragment_shader(void)
{
   nir_builder b = nir_builder_init_simple_shader(MESA_SHADER_FRAGMENT,
                                                   pco_nir_options(),
                                                   "glbench_conditionals_fs");

   nir_def *frag_coord = nir_load_frag_coord(&b);
   nir_def *y_transform = nir_load_push_constant(&b,
                                                  2,
                                                  32,
                                                  nir_imm_int(&b, 0),
                                                  .base = 0,
                                                  .range = 4);
   nir_def *y = nir_ffma(&b,
                         nir_channel(&b, frag_coord, 1),
                         nir_channel(&b, y_transform, 0),
                         nir_channel(&b, y_transform, 1));
   /* Preserve the captured Gallium NIR operation order exactly.  Reordering
    * this to (frag_x * y) * 0.0001 is mathematically equivalent but changes
    * float32 rounding at a small number of RGBA8 quantization boundaries. */
   nir_def *scaled_x =
      nir_fmul_imm(&b, nir_channel(&b, frag_coord, 0), 0.0001f);
   nir_def *phase = nir_ffract(&b, nir_fmul(&b, scaled_x, y));
#define QUANTIZE_MEDIUMP(value)                                             \
   nir_f2f32(&b, nir_f2f16_rtne(&b, (value)))
   nir_def *phase_mediump = QUANTIZE_MEDIUMP(phase);
   nir_def *condition =
      nir_fge(&b, phase_mediump, nir_imm_float(&b, 0.5f));
   nir_def *twice_product =
      QUANTIZE_MEDIUMP(nir_fmul_imm(&b, phase_mediump, 2.0f));
   nir_def *twice = QUANTIZE_MEDIUMP(nir_ffract(&b, twice_product));
   nir_def *thrice_product =
      QUANTIZE_MEDIUMP(nir_fmul_imm(&b, phase_mediump, 3.0f));
   nir_def *thrice = QUANTIZE_MEDIUMP(nir_ffract(&b, thrice_product));
   nir_def *color = nir_bcsel(&b, condition, twice, thrice);
#undef QUANTIZE_MEDIUMP

   for (unsigned component = 0; component < 3; ++component)
      nir_frag_store_pco(&b, color, .base = component);
   nir_frag_store_pco(&b, nir_imm_float(&b, 1.0f), .base = 3);
   nir_jump(&b, nir_jump_return);
   return b.shader;
}

static void allocate_push_constants(pco_data *data)
{
   if (!data->common.push_consts.used)
      return;

   data->common.push_consts.range = (pco_range){
      .start = data->common.shareds,
      .count = data->common.push_consts.used,
   };
   data->common.shareds += data->common.push_consts.used;
}

static pco_shader *compile_shader(pco_ctx *ctx,
                                  nir_shader *nir,
                                  pco_data *data)
{
   pco_lower_nir(ctx, nir, data);
   pco_postprocess_nir(ctx, nir, data);
   allocate_push_constants(data);

   pco_shader *shader = pco_trans_nir(ctx, nir, data, NULL);
   if (!shader)
      return NULL;
   pco_process_ir(ctx, shader);
   pco_encode_ir(ctx, shader);
   return shader;
}

static int write_binary(const char *path, pco_shader *shader)
{
   FILE *file = fopen(path, "wb");
   if (!file) {
      fprintf(stderr, "fopen(%s): %s\n", path, strerror(errno));
      return 1;
   }

   const unsigned size = pco_shader_binary_size(shader);
   const size_t written = fwrite(pco_shader_binary_data(shader), 1, size, file);
   const int close_result = fclose(file);
   if (written != size || close_result != 0) {
      fprintf(stderr, "failed to write complete PCO binary: %s\n", path);
      return 1;
   }

   fprintf(stderr, "wrote %u bytes of Mesa PCO binary to %s\n", size, path);
   return 0;
}

int main(int argc, char **argv)
{
   if (argc != 3) {
      fprintf(stderr, "Usage: %s VERTEX.bin FRAGMENT.bin\n", argv[0]);
      return 2;
   }

   void *mem_ctx = ralloc_context(NULL);
   struct pvr_device_info dev_info;
   struct pvr_device_runtime_info runtime_info = { 0 };
   if (!pvr_device_info_init_public_name(&dev_info, "gx6250")) {
      fprintf(stderr, "Mesa does not recognize the public gx6250 target\n");
      ralloc_free(mem_ctx);
      return 1;
   }

   pco_ctx *ctx = pco_ctx_create(&dev_info, &runtime_info, mem_ctx);
   nir_shader *vertex_nir = build_vertex_shader();
   nir_shader *fragment_nir = build_fragment_shader();
   pco_data vertex_data = { 0 };
   pco_data fragment_data = { 0 };

   vertex_data.vs.attrib_formats[VERT_ATTRIB_GENERIC0] =
      PIPE_FORMAT_R32G32B32_FLOAT;
   vertex_data.vs.attribs[VERT_ATTRIB_GENERIC0] = (pco_range){
      .start = 0,
      .count = 4,
   };
   vertex_data.common.vtxins = 4;

   pco_preprocess_nir(ctx, vertex_nir);
   pco_preprocess_nir(ctx, fragment_nir);
   pco_link_nir(ctx,
                vertex_nir,
                fragment_nir,
                &vertex_data,
                &fragment_data);
   pco_rev_link_nir(ctx, vertex_nir, fragment_nir);

   vertex_data.vs.varyings[VARYING_SLOT_POS] = (pco_range){
      .start = 0,
      .count = 4,
   };
   vertex_data.vs.vtxouts = 4;

   pco_shader *vertex = compile_shader(ctx, vertex_nir, &vertex_data);
   pco_shader *fragment = compile_shader(ctx, fragment_nir, &fragment_data);
   if (!vertex || !fragment) {
      fprintf(stderr, "PCO conditionals translation failed\n");
      ralloc_free(vertex);
      ralloc_free(fragment);
      ralloc_free(vertex_nir);
      ralloc_free(fragment_nir);
      ralloc_free(mem_ctx);
      return 1;
   }

   pco_print_shader(vertex, stdout, "conditionals vertex");
   pco_print_binary(vertex, stdout, "conditionals vertex");
   pco_print_shader(fragment, stdout, "conditionals fragment");
   pco_print_binary(fragment, stdout, "conditionals fragment");
   const int result = write_binary(argv[1], vertex) ||
                      write_binary(argv[2], fragment);

   ralloc_free(vertex);
   ralloc_free(fragment);
   ralloc_free(vertex_nir);
   ralloc_free(fragment_nir);
   ralloc_free(mem_ctx);
   return result;
}
